#' Direct SQL-Based Toxicity Assignment
#'
#' This module provides a clean architecture where assign_toxicity() queries
#' the SQLite database directly without loading data into global variables.
#' This eliminates global variable pollution and provides better performance.
#'
#' @importFrom DBI dbConnect dbDisconnect dbGetQuery
#' @importFrom RSQLite SQLite
#' @importFrom dplyr mutate case_when na_if

#' Enhanced Assign Toxicity with Direct SQL Queries
#'
#' Enhanced version of assign_toxicity that queries SQLite database directly
#' without loading data into global variables. Maintains the exact same interface
#' and functionality as the original function while providing better architecture.
#'
#' @param data Your data containing at least InChIKey
#' @param toxtree_result The *.csv file generated by Toxtree batch processing.
#' @param check_updates Logical, whether to check for available updates (default: TRUE)
#' @param auto_update Logical, whether to automatically apply available updates (default: TRUE)
#' @param show_update_details Logical, whether to show detailed update information (default: TRUE)
#' @return A data.frame or tibble with toxicity assigned (same as original function)
#' @export
assign_toxicity <- function(data, toxtree_result = "toxtree_results.csv",
                           check_updates = TRUE, auto_update = TRUE, show_update_details = TRUE) {

  message("🧪 FCMSafety Toxicity Assignment with Direct SQL Queries")
  message(paste(rep("=", 60), collapse = ""))

  # Step 1: Check for database updates if requested
  if (check_updates) {
    message("🔍 Checking for database updates...")

    update_info <- check_available_updates(c("svhc", "cmr", "iarc", "eu_sml"))

    if (length(update_info$available) > 0) {
      message("🆕 Updates available for: ", paste(update_info$available, collapse = ", "))

      if (auto_update) {
        message("🔄 Auto-updating databases...")

        # Perform updates for each available database
        update_results <- list()
        total_changes <- 0

        for (db_name in update_info$available) {
          message("\n📥 Updating ", toupper(db_name), " database...")

          update_result <- tryCatch({
            if (db_name == "svhc") {
              update_svhc()
            } else if (db_name == "cmr") {
              update_cmr()
            } else if (db_name == "iarc") {
              update_iarc()
            } else if (db_name == "eu_sml") {
              update_eu_sml()
            } else {
              list(success = FALSE, error = paste("Update function not available for", db_name))
            }
          }, error = function(e) {
            list(success = FALSE, error = e$message)
          })

          update_results[[db_name]] <- update_result

          if (update_result$success) {
            message("✅ ", toupper(db_name), " update completed successfully")
            if (!is.null(update_result$changes)) {
              changes <- update_result$changes
              db_changes <- changes$total_added + changes$total_removed + changes$total_modified
              total_changes <- total_changes + db_changes

              if (show_update_details && db_changes > 0) {
                message("   📊 Changes: +", changes$total_added, " added, -", changes$total_removed,
                       " removed, ~", changes$total_modified, " modified")
              }
            }
          } else {
            message("❌ ", toupper(db_name), " update failed: ", update_result$error)
          }
        }

        # Summary of all updates
        successful_updates <- sum(sapply(update_results, function(x) x$success))

        if (successful_updates > 0) {
          message("\n✅ Database updates completed!")
          message("📊 Successfully updated ", successful_updates, " out of ", length(update_info$available), " databases")
          if (total_changes > 0) {
            message("📈 Total changes applied: ", total_changes, " records")
          }
        } else {
          message("\n⚠️  All updates failed, proceeding with existing data")
        }
      } else {
        message("💡 Auto-update disabled. Run with auto_update = TRUE to apply updates")
        message("💡 Or use update_databases_interactive() for manual control")
      }
    } else {
      message("✅ All databases are up to date")
    }
  }

  # Step 2: Verify SQLite database exists and is accessible
  tryCatch({
    db_status <- check_database_status()
    if (!db_status$initialized) {
      stop("SQLite database not initialized. Run setup_fcmsafety_database() first.")
    }
  }, error = function(e) {
    stop("Database error: ", e$message, "\nPlease ensure the SQLite database is properly set up.")
  })

  # Step 3: Read and validate toxtree results
  if (!file.exists(toxtree_result)) {
    stop("Toxtree result file not found: ", toxtree_result,
         "\nPlease ensure the file exists or provide the correct path.")
  }

  tox <- utils::read.csv(toxtree_result)

  # Validate input data
  if (!"InChIKey" %in% names(data)) {
    stop("Input data must contain an 'InChIKey' column")
  }

  if (!"SMILES" %in% names(data)) {
    message("⚠️  No SMILES column found in input data. Cramer rules assignment may be limited.")
  }

  # Step 4: Perform toxicity assignment using direct SQL queries
  message("\n🔬 Performing toxicity assignment with direct SQL queries...")

  # Get database connection
  con <- get_db_connection()
  on.exit(DBI::dbDisconnect(con))

  # Extract InChIKeys for SQL queries
  inchikeys <- data$InChIKey[!is.na(data$InChIKey)]

  if (length(inchikeys) == 0) {
    message("⚠️  No valid InChIKeys found in input data")
    return(data)
  }

  # Create SQL IN clause for InChIKeys
  inchikey_list <- paste0("'", inchikeys, "'", collapse = ",")

  # Query each database directly
  message("📊 Querying regulatory databases...")

  # SVHC database
  svhc_matches <- query_database_matches(con, "svhc", inchikey_list, "InChIKey")
  message("   SVHC: ", length(svhc_matches), " matches found")

  # CMR database
  cmr_matches <- query_database_matches(con, "cmr", inchikey_list, "InChIKey")
  message("   CMR: ", length(cmr_matches), " matches found")

  # CMR Suspect database
  cmr_suspect_matches <- query_database_matches(con, "cmr_suspect", inchikey_list, "InChIKey")
  message("   CMR Suspect: ", length(cmr_suspect_matches), " matches found")

  # EDC database
  edc_matches <- query_database_matches(con, "edc", inchikey_list, "InChIKey")
  message("   EDC: ", length(edc_matches), " matches found")

  # IARC database with group classification
  iarc_data <- query_iarc_data(con, inchikey_list)
  iarc_matches <- nrow(iarc_data)
  message("   IARC: ", iarc_matches, " matches found")

  # EU SML database
  eu_sml_data <- query_eu_sml_data(con, inchikey_list)
  eu_sml_matches <- nrow(eu_sml_data)
  message("   EU SML: ", eu_sml_matches, " matches found")

  # EU SML Group database
  eu_sml_group_data <- query_eu_sml_group_data(con, inchikey_list)

  # China SML database
  china_sml_data <- query_china_sml_data(con, inchikey_list)
  china_sml_matches <- nrow(china_sml_data)
  message("   China SML: ", china_sml_matches, " matches found")

  # Step 5: Apply toxicity assignment logic using SQL results
  result_data <- data %>%
    dplyr::mutate(
      Cramer_rules = if ("SMILES" %in% names(data)) {
        tox$Cramer.rules[match(SMILES, tox$SMILES)]
      } else {
        NA
      },
      # Check if compounds present in any of the databases using SQL results
      SVHC = dplyr::case_when(InChIKey %in% svhc_matches ~ "Y"),
      CMR = dplyr::case_when(InChIKey %in% cmr_matches ~ "Y"),
      CMR_suspect = dplyr::case_when(InChIKey %in% cmr_suspect_matches ~ "Y"),
      EDC = dplyr::case_when(InChIKey %in% edc_matches ~ "Y"),
      IARC = iarc_data$group_classification[match(InChIKey, iarc_data$InChIKey)] %>% dplyr::na_if("3"),
      EU_SML = eu_sml_data$sml[match(InChIKey, eu_sml_data$InChIKey)],
      EU_SML_group = eu_sml_data$sml_group[match(InChIKey, eu_sml_data$InChIKey)],
      China_SML = china_sml_data$sml_value[match(InChIKey, china_sml_data$InChIKey)],
      China_SML_group = NA_character_  # China SML group not available in current schema
    ) %>%
    dplyr::mutate(
      # Handle EU SML logic - use group SML if individual SML is not available
      EU_SML = dplyr::case_when(
        is.na(EU_SML) & !is.na(EU_SML_group) ~
          eu_sml_group_data$sml[match(EU_SML_group, eu_sml_group_data$group_no)],
        TRUE ~ EU_SML
      ),
      # Handle China SML logic (convert to character to avoid type conflicts)
      China_SML = dplyr::case_when(
        is.na(China_SML) & !is.na(China_SML_group) ~ China_SML_group,
        TRUE ~ as.character(China_SML)
      ),
      # Mark group SML with asterisk
      EU_SML = dplyr::case_when(
        !is.na(EU_SML_group) ~ paste0(EU_SML, "*"),
        TRUE ~ as.character(EU_SML)
      ),
      China_SML = dplyr::case_when(
        !is.na(China_SML_group) ~ paste0(China_SML, "*"),
        TRUE ~ as.character(China_SML)
      ),
      # Remove temporary columns
      EU_SML_group = NULL,
      China_SML_group = NULL
    )

  # Replace NA with "-"
  result_data[is.na(result_data)] <- "-"

  # Relocate toxicity columns (same logic as original)
  if ("Flavornet" %in% colnames(result_data)) {
    result_data <- dplyr::relocate(result_data, Cramer_rules:China_SML, .after = Flavornet)
  } else if ("CAS_retrieved" %in% colnames(result_data)) {
    result_data <- dplyr::relocate(result_data, Cramer_rules:China_SML, .after = CAS_retrieved)
  } else if ("ExactMass" %in% colnames(result_data)) {
    result_data <- dplyr::relocate(result_data, Cramer_rules:China_SML, .after = ExactMass)
  }

  # Step 6: Provide summary of results
  message("✅ Toxicity assignment completed!")

  # Count assignments
  svhc_count <- sum(result_data$SVHC == "Y", na.rm = TRUE)
  cmr_count <- sum(result_data$CMR == "Y", na.rm = TRUE)
  cmr_suspect_count <- sum(result_data$CMR_suspect == "Y", na.rm = TRUE)
  edc_count <- sum(result_data$EDC == "Y", na.rm = TRUE)
  iarc_count <- sum(result_data$IARC != "-", na.rm = TRUE)
  eu_sml_count <- sum(result_data$EU_SML != "-", na.rm = TRUE)
  china_sml_count <- sum(result_data$China_SML != "-", na.rm = TRUE)

  message("\n📊 Toxicity Assignment Summary:")
  message("   Total compounds processed: ", nrow(result_data))
  message("   SVHC matches: ", svhc_count)
  message("   CMR matches: ", cmr_count)
  message("   CMR suspect matches: ", cmr_suspect_count)
  message("   EDC matches: ", edc_count)
  message("   IARC matches: ", iarc_count)
  message("   EU SML matches: ", eu_sml_count)
  message("   China SML matches: ", china_sml_count)

  total_matches <- svhc_count + cmr_count + cmr_suspect_count + edc_count + iarc_count + eu_sml_count + china_sml_count
  message("   Total database matches: ", total_matches)

  if (total_matches > 0) {
    message("⚠️  ", total_matches, " compounds found in regulatory databases - review carefully!")
  } else {
    message("✅ No compounds found in regulatory databases")
  }

  message(paste(rep("=", 60), collapse = ""))

  return(result_data)
}

#' Query Database Matches
#'
#' Helper function to query a database table for InChIKey matches.
#'
#' @param con Database connection
#' @param table_name Name of the table to query
#' @param inchikey_list Comma-separated list of InChIKeys for SQL IN clause
#' @param key_column Name of the InChIKey column in the table
#' @return Vector of matching InChIKeys
query_database_matches <- function(con, table_name, inchikey_list, key_column = "InChIKey") {
  query <- paste0("SELECT DISTINCT ", key_column, " FROM ", table_name,
                  " WHERE ", key_column, " IN (", inchikey_list, ")")

  result <- tryCatch({
    DBI::dbGetQuery(con, query)
  }, error = function(e) {
    message("Warning: Error querying ", table_name, ": ", e$message)
    data.frame()
  })

  if (nrow(result) > 0) {
    return(result[[key_column]])
  } else {
    return(character(0))
  }
}

#' Query IARC Data
#'
#' Helper function to query IARC database for group classifications.
#'
#' @param con Database connection
#' @param inchikey_list Comma-separated list of InChIKeys for SQL IN clause
#' @return Data frame with InChIKey and group_classification
query_iarc_data <- function(con, inchikey_list) {
  query <- paste0("SELECT InChIKey, group_classification FROM iarc WHERE InChIKey IN (", inchikey_list, ")")

  result <- tryCatch({
    DBI::dbGetQuery(con, query)
  }, error = function(e) {
    message("Warning: Error querying IARC: ", e$message)
    data.frame(InChIKey = character(0), group_classification = character(0))
  })

  return(result)
}

#' Query EU SML Data
#'
#' Helper function to query EU SML database for SML values and groups.
#'
#' @param con Database connection
#' @param inchikey_list Comma-separated list of InChIKeys for SQL IN clause
#' @return Data frame with InChIKey, sml, and sml_group
query_eu_sml_data <- function(con, inchikey_list) {
  query <- paste0("SELECT InChIKey, sml, sml_group FROM eu_sml WHERE InChIKey IN (", inchikey_list, ")")

  result <- tryCatch({
    DBI::dbGetQuery(con, query)
  }, error = function(e) {
    message("Warning: Error querying EU SML: ", e$message)
    data.frame(InChIKey = character(0), sml = numeric(0), sml_group = character(0))
  })

  return(result)
}

#' Query EU SML Group Data
#'
#' Helper function to query EU SML Group database.
#'
#' @param con Database connection
#' @param inchikey_list Comma-separated list of InChIKeys for SQL IN clause
#' @return Data frame with group_no and sml
query_eu_sml_group_data <- function(con, inchikey_list) {
  query <- paste0("SELECT group_no, sml FROM eu_sml_group WHERE InChIKey IN (", inchikey_list, ")")

  result <- tryCatch({
    DBI::dbGetQuery(con, query)
  }, error = function(e) {
    message("Warning: Error querying EU SML Group: ", e$message)
    data.frame(group_no = character(0), sml = numeric(0))
  })

  return(result)
}

#' Query China SML Data
#'
#' Helper function to query China SML database.
#'
#' @param con Database connection
#' @param inchikey_list Comma-separated list of InChIKeys for SQL IN clause
#' @return Data frame with InChIKey and sml_value
query_china_sml_data <- function(con, inchikey_list) {
  # Check if china_sml table has any records first
  count_query <- "SELECT COUNT(*) as count FROM china_sml"
  count_result <- tryCatch({
    DBI::dbGetQuery(con, count_query)$count[1]
  }, error = function(e) {
    0
  })

  if (count_result == 0) {
    return(data.frame(InChIKey = character(0), sml_value = character(0)))
  }

  query <- paste0("SELECT InChIKey, sml_value FROM china_sml WHERE InChIKey IN (", inchikey_list, ")")

  result <- tryCatch({
    DBI::dbGetQuery(con, query)
  }, error = function(e) {
    message("Warning: Error querying China SML: ", e$message)
    data.frame(InChIKey = character(0), sml_value = character(0))
  })

  return(result)
}
